#githubWorkFlows
name: Test

on: [ push ]

run-name: ${{ github.actor }} is learning GitHub Actions

jobs:
  check-bats-version:
    # где запускаем
    runs-on: ubuntu-latest
    # что делаем
    steps:
      # скачиваем репозиторий
      - uses: actions/checkout@v3
        # настраиваем java
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '11'
      # запускаем тесты
      - run: ./gradlew clean test

