#githubWorkFlows
name: Test

on: [ push ]

run-name: ${{ github.actor }} is learning GitHub Actions

jobs:
  check-bats-version:
    # где запускаем
    runs-on: ubuntu-latest
    # что делаем
    steps:
      # скачиваем репозиторий
      - name: <Скачиваем репазиторий>
        uses: actions/checkout@v3
        # настраиваем java
      - name: <Настройка Java>
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '11'
      - name: <Настраиваем Selenoid>
        uses: Xotabu4/selenoid-github-action@v2
      # запускаем тесты
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

