#githubWorkFlows
name: Test

on: workflow_dispatch

run-name: ${{ github.actor }} is learning GitHub Actions

jobs:
  check-bats-version:
    # где запускаем
    runs-on: ubuntu-latest
    # что делаем
    steps:
      # скачиваем репозиторий
      - name: Скачиваем репазиторий
        uses: actions/checkout@v3
        # настраиваем java
      - name: Настройка Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Настраиваем Selenoid
        uses: Xotabu4/selenoid-github-action@v2

      # запускаем тесты
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

      # Настройка Allure
      - name: Скачиваем историю тестов
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Генерируем отчет
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Публикуем отчет в Github
        uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history